---
- hosts: swarm
  become: yes
  become_user: root
  roles:
    - { role: jzmch.ansible-docker, docker_users: vagrant }

- hosts: managers
  serial: 1
  roles:
    - { role: docker-swarm-init, when: initial_leader is defined }
    - { role: docker-swarm-manager, when: initial_leader is not defined }

- hosts: workers
  serial: 1
  roles:
    - { role: docker-swarm-worker }
