---
- hosts: swarm
  become: yes
  become_user: root
  roles:
    - { role: jzmch.ansible-docker, docker_users: vagrant }

- hosts: managers
  serial: 1
  roles:
    - { role: docker-swarm-init, when: "inventory_hostname == groups['managers'][0]" }
    - { role: docker-swarm-manager, when: "inventory_hostname != groups['managers'][0]" }

- hosts: workers
  serial: 1
  roles:
    - { role: docker-swarm-worker }
