---
- name: Initialize swarm
  shell: "{{ docker_binary }} swarm init --advertise-addr {{ swarm_manager_ips[0] }}"
  when: docker_node_ls.rc != 0 and swarm_manager_ips is defined

- name: Get swarm manager token
  shell: "{{ docker_binary }} swarm join-token manager -q"
  register: docker_swarm_manager_token_query

- name: Get swarm worker token
  shell: "{{ docker_binary }} swarm join-token worker -q"
  register: docker_swarm_worker_token_query

- name: Set swarm token as facts
  set_fact:
    docker_swarm_manager_token: "{{ docker_swarm_manager_token_query.stdout }}"
    docker_swarm_worker_token: "{{ docker_swarm_worker_token_query.stdout }}"
