---
- name: Check if already part of swarm
  command: "{{ docker_binary }} node ls -q"
  register: docker_node_ls
  changed_when: no
  ignore_errors: yes

- name: Join cluster as a manager
  command: "{{ docker_binary }} swarm join --token {{ lookup('file', docker_swarm_worker_token_file) }} {{ swarm_manager_ips[0] }}:2377"
  when: docker_node_ls.rc != 0 and inventory_hostname != groups["managers"][0]
